warl_test_list = [
    'mpp_warl'
]

privilege_test_pool = [
    ['I-EBREAK-01' , " 'i' in isa"],
    ['I-ECALL-01' , " 'i' in isa"],
    ['I-MISALIGN_JMP-01' , " 'i' in isa"],
    ['I-ISALIGN_LDST-02' , " 'i' in isa"],
]


unprivilege_test_pool = [
    ['M-DIV-01', 'rv32im', " 'm' in isa"],
    ['M-DIVU-01', 'rv32im'," 'm' in isa"],
    ['M-MULH-01', 'rv32im'," 'm' in isa"],
    ['M-MULHSU-01','rv32im', " 'm' in isa"],
    ['M-MULHU-01','rv32im', " 'm' in isa"],
    ['M-MUL-01','rv32im', " 'm' in isa"],
    ['M-REM-01','rv32im', " 'm' in isa"],
    ['M-REMU-01','rv32im', " 'm' in isa"],
    ['I-ADD-01' ,'rv32i', " 'i' in isa"],
    ['I-ADDI-01' ,'rv32i', " 'i' in isa"],
    ['I-AND-01' ,'rv32i', " 'i' in isa"],
    ['I-ANDI-01' ,'rv32i', " 'i' in isa"],
    ['I-AUIPC-01' ,'rv32i', " 'i' in isa"],
    ['I-BEQ-01' ,'rv32i', " 'i' in isa"],
    ['I-BNE-01' ,'rv32i', " 'i' in isa"],
    ['I-BGE-01' ,'rv32i', " 'i' in isa"],
    ['I-BGEU-01' ,'rv32i', " 'i' in isa"],
    ['I-BLT-01' ,'rv32i', " 'i' in isa"],
    ['I-BLTU-01' ,'rv32i', " 'i' in isa"],
    ['I-CSRRW-01' ,'rv32i', " 'i' in isa"],
    ['I-CSRRC-01' ,'rv32i', " 'i' in isa"],
    ['I-CSRRWI-01' ,'rv32i', " 'i' in isa"],
    ['I-CSRRCI-01' ,'rv32i', " 'i' in isa"],
    ['I-CSRRS-01' ,'rv32i', " 'i' in isa"],
    ['I-CSRRSI-01' ,'rv32i', " 'i' in isa"],
    ['I-DELAY_SLOTS-01' ,'rv32i', " 'i' in isa"],
    ['I-ENDIANESS-01' ,'rv32i', " 'i' in isa"],
    ['I-FENCE.I-01' ,'rv32i', " 'i' in isa"],
    ['I-IO' ,'rv32i', " 'i' in isa"],
    ['I-JAL-01' ,'rv32i', " 'i' in isa"],
    ['I-JALR-01' ,'rv32i', " 'i' in isa"],
    ['I-LB-01' ,'rv32i', " 'i' in isa"],
    ['I-LBU-01' ,'rv32i', " 'i' in isa"],
    ['I-LH-01' ,'rv32i', " 'i' in isa"],
    ['I-LHU-01' ,'rv32i', " 'i' in isa"],
    ['I-LW-01' ,'rv32i', " 'i' in isa"],
    ['I-LUI-01' ,'rv32i', " 'i' in isa"],
    ['I-NOP-01' ,'rv32i', " 'i' in isa"],
    ['I-OR-01' ,'rv32i', " 'i' in isa"],
    ['I-ORI-01' ,'rv32i', " 'i' in isa"],
    ['I-RF_size-01' ,'rv32i', " 'i' in isa"],
    ['I-RF_width-01' ,'rv32i', " 'i' in isa"],
    ['I-RF_x0-01' ,'rv32i', " 'i' in isa"],
    ['I-SB-01' ,'rv32i', " 'i' in isa"],
    ['I-SH-01' ,'rv32i', " 'i' in isa"],
    ['I-SLL-01' ,'rv32i', " 'i' in isa"],
    ['I-SLLI-01' ,'rv32i', " 'i' in isa"],
    ['I-SLT-01' ,'rv32i', " 'i' in isa"],
    ['I-SLTI-01' ,'rv32i', " 'i' in isa"],
    ['I-SLTIU-01' ,'rv32i', " 'i' in isa"],
    ['I-SLTU-01' ,'rv32i', " 'i' in isa"],
    ['I-SRA-01' ,'rv32i', " 'i' in isa"],
    ['I-SRAI-01' ,'rv32i', " 'i' in isa"],
    ['I-SRL-01' ,'rv32i', " 'i' in isa"],
    ['I-SRLI-01' ,'rv32i', " 'i' in isa"],
    ['I-SW-01' ,'rv32i', " 'i' in isa"],
    ['I-SUB-01' ,'rv32i', " 'i' in isa"],
    ['I-XOR-01' ,'rv32i', " 'i' in isa"],
    ['I-XORI-01' ,'rv32i', " 'i' in isa"],
    ['C-ADD', 'rv32imc', " 'c' in isa"],
    ['C-ADDI', 'rv32imc', " 'c' in isa"],
    ['C-ADDI16SP', 'rv32imc', " 'c' in isa"],
    ['C-ADDI4SPN', 'rv32imc', " 'c' in isa"],
    ['C-AND', 'rv32imc', " 'c' in isa"],
    ['C-ANDI', 'rv32imc', " 'c' in isa"],
    ['C-BEQZ', 'rv32imc', " 'c' in isa"],
    ['C-BNEZ', 'rv32imc', " 'c' in isa"],
    ['C-J', 'rv32imc', " 'c' in isa"],
    ['C-JAL', 'rv32imc', " 'c' in isa"],
    ['C-JALR', 'rv32imc', " 'c' in isa"],
    ['C-JR', 'rv32imc', " 'c' in isa"],
    ['C-LI', 'rv32imc', " 'c' in isa"],
    ['C-LUI', 'rv32imc', " 'c' in isa"],
    ['C-LW', 'rv32imc', " 'c' in isa"],
    ['C-LWSP', 'rv32imc', " 'c' in isa"],
    ['C-MV', 'rv32imc', " 'c' in isa"],
    ['C-OR', 'rv32imc', " 'c' in isa"],
    ['C-SLLI', 'rv32imc', " 'c' in isa"],
    ['C-SRAI', 'rv32imc', " 'c' in isa"],
    ['C-SRLI', 'rv32imc', " 'c' in isa"],
    ['C-SUB', 'rv32imc', " 'c' in isa"],
    ['C-SW', 'rv32imc', " 'c' in isa"],
    ['C-SWSP', 'rv32imc', " 'c' in isa"],
    ['RV32A-AMOADD-W', 'rv32ia', " 'a' in isa"],
    ['RV32A-AMOAND-W', 'rv32ia', " 'a' in isa"],
    ['RV32A-AMOMAXU-W', 'rv32ia', " 'a' in isa"],
    ['RV32A-AMOMAX-W', 'rv32ia', " 'a' in isa"],
    ['RV32A-AMOMINU-W', 'rv32ia', " 'a' in isa"],
    ['RV32A-AMOMIN-W', 'rv32ia', " 'a' in isa"],
    ['RV32A-AMOOR-W', 'rv32ia', " 'a' in isa"],
    ['RV32A-AMOSWAP-W', 'rv32ia', " 'a' in isa"],
    ['RV32A-AMOXOR-W', 'rv32ia', " 'a' in isa"],
    ['RV32A-LRSC', 'rv32ia', " 'a' in isa"],
]
