warl_test_list = [
    'mpp_warl'
]

privilege_test_pool = [
    #['I-EBREAK-01' , 'I in ISA'],
    #['I-ECALL-01' , 'I in ISA'],
    #['I-MISALIGN_JMP-01' , 'I in ISA'],
    #['I-ISALIGN_LDST-02' , 'I in ISA'],
]


unprivilege_test_pool = [
    ['M-DIV-01', 'rv32im', 'M in ISA'],
    ['M-DIVU-01', 'rv32im','M in ISA'],
    ['M-MULH-01', 'rv32im','M in ISA'],
    ['M-MULHSU-01','rv32im', 'M in ISA'],
    ['M-MULHU-01','rv32im', 'M in ISA'],
    ['M-MUL-01','rv32im', 'M in ISA'],
    ['M-REM-01','rv32im', 'M in ISA'],
    ['M-REMU-01','rv32im', 'M in ISA'],
    ['I-ADD-01' ,'rv32i', 'I in ISA'],
    ['I-ADDI-01' ,'rv32i', 'I in ISA'],
    ['I-AND-01' ,'rv32i', 'I in ISA'],
    ['I-ANDI-01' ,'rv32i', 'I in ISA'],
    ['I-AUIPC-01' ,'rv32i', 'I in ISA'],
    ['I-BEQ-01' ,'rv32i', 'I in ISA'],
    ['I-BNE-01' ,'rv32i', 'I in ISA'],
    ['I-BGE-01' ,'rv32i', 'I in ISA'],
    ['I-BGEU-01' ,'rv32i', 'I in ISA'],
    ['I-BLT-01' ,'rv32i', 'I in ISA'],
    ['I-BLTU-01' ,'rv32i', 'I in ISA'],
    ['I-CSRRW-01' ,'rv32i', 'I in ISA'],
    ['I-CSRRC-01' ,'rv32i', 'I in ISA'],
    ['I-CSRRWI-01' ,'rv32i', 'I in ISA'],
    ['I-CSRRCI-01' ,'rv32i', 'I in ISA'],
    ['I-CSRRS-01' ,'rv32i', 'I in ISA'],
    ['I-CSRRSI-01' ,'rv32i', 'I in ISA'],
    ['I-DELAY_SLOTS-01' ,'rv32i', 'I in ISA'],
    ['I-ENDIANESS-01' ,'rv32i', 'I in ISA'],
    ['I-FENCE.I-01' ,'rv32i', 'I in ISA'],
    ['I-IO' ,'rv32i', 'I in ISA'],
    ['I-JAL-01' ,'rv32i', 'I in ISA'],
    ['I-JALR-01' ,'rv32i', 'I in ISA'],
    ['I-LB-01' ,'rv32i', 'I in ISA'],
    ['I-LBU-01' ,'rv32i', 'I in ISA'],
    ['I-LH-01' ,'rv32i', 'I in ISA'],
    ['I-LHU-01' ,'rv32i', 'I in ISA'],
    ['I-LW-01' ,'rv32i', 'I in ISA'],
    ['I-LUI-01' ,'rv32i', 'I in ISA'],
    ['I-NOP-01' ,'rv32i', 'I in ISA'],
    ['I-OR-01' ,'rv32i', 'I in ISA'],
    ['I-ORI-01' ,'rv32i', 'I in ISA'],
    ['I-RF_size-01' ,'rv32i', 'I in ISA'],
    ['I-RF_width-01' ,'rv32i', 'I in ISA'],
    ['I-RF_x0-01' ,'rv32i', 'I in ISA'],
    ['I-SB-01' ,'rv32i', 'I in ISA'],
    ['I-SH-01' ,'rv32i', 'I in ISA'],
    ['I-SLL-01' ,'rv32i', 'I in ISA'],
    ['I-SLLI-01' ,'rv32i', 'I in ISA'],
    ['I-SLT-01' ,'rv32i', 'I in ISA'],
    ['I-SLTI-01' ,'rv32i', 'I in ISA'],
    ['I-SLTIU-01' ,'rv32i', 'I in ISA'],
    ['I-SLTU-01' ,'rv32i', 'I in ISA'],
    ['I-SRA-01' ,'rv32i', 'I in ISA'],
    ['I-SRAI-01' ,'rv32i', 'I in ISA'],
    ['I-SRL-01' ,'rv32i', 'I in ISA'],
    ['I-SRLI-01' ,'rv32i', 'I in ISA'],
    ['I-SW-01' ,'rv32i', 'I in ISA'],
    ['I-SUB-01' ,'rv32i', 'I in ISA'],
    ['I-XOR-01' ,'rv32i', 'I in ISA'],
    ['I-XORI-01' ,'rv32i', 'I in ISA']
]
